/*
 * Copyright (C) 2011
 * @author John Erol M. Evangelista
 * 
 * Academic Requirement for CS 11 HTYZ 1st Sem AY 2011-2012
 * Under the guidance of Prof. Mario Carreon
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * Website: http://opensource.org/licenses/gpl-license.php
 * 
 * 
 */

/*
 * EmployeeProfile.java
 *
 * Created on Jan 20, 2012, 10:27:14 PM
 */

/**
 *
 * @author erol
 */
public class EmployeeProfile extends javax.swing.JFrame {

    /** Creates new form EmployeeProfile */
    public EmployeeProfile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane15 = new javax.swing.JTabbedPane();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane19 = new javax.swing.JTabbedPane();
        jTabbedPane20 = new javax.swing.JTabbedPane();
        jTabbedPane21 = new javax.swing.JTabbedPane();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane23 = new javax.swing.JTabbedPane();
        jTabbedPane24 = new javax.swing.JTabbedPane();
        jTabbedPane25 = new javax.swing.JTabbedPane();
        jTabbedPane26 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane27 = new javax.swing.JTabbedPane();
        jTabbedPane28 = new javax.swing.JTabbedPane();
        jTabbedPane29 = new javax.swing.JTabbedPane();
        jTabbedPane30 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane31 = new javax.swing.JTabbedPane();
        jTabbedPane32 = new javax.swing.JTabbedPane();
        jTabbedPane33 = new javax.swing.JTabbedPane();
        jTabbedPane34 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jTabbedPane35 = new javax.swing.JTabbedPane();
        jTabbedPane36 = new javax.swing.JTabbedPane();
        jTabbedPane37 = new javax.swing.JTabbedPane();
        jTabbedPane38 = new javax.swing.JTabbedPane();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jTabbedPane39 = new javax.swing.JTabbedPane();
        jTabbedPane40 = new javax.swing.JTabbedPane();
        jTabbedPane41 = new javax.swing.JTabbedPane();
        jTabbedPane42 = new javax.swing.JTabbedPane();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jTabbedPane43 = new javax.swing.JTabbedPane();
        jTabbedPane44 = new javax.swing.JTabbedPane();
        jTabbedPane45 = new javax.swing.JTabbedPane();
        jTabbedPane46 = new javax.swing.JTabbedPane();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jTabbedPane47 = new javax.swing.JTabbedPane();
        jTabbedPane48 = new javax.swing.JTabbedPane();
        jTabbedPane49 = new javax.swing.JTabbedPane();
        jTabbedPane50 = new javax.swing.JTabbedPane();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jTabbedPane51 = new javax.swing.JTabbedPane();
        jTabbedPane52 = new javax.swing.JTabbedPane();
        jTabbedPane53 = new javax.swing.JTabbedPane();
        jTabbedPane54 = new javax.swing.JTabbedPane();
        jTabbedPane13 = new javax.swing.JTabbedPane();
        jTabbedPane55 = new javax.swing.JTabbedPane();
        jTabbedPane56 = new javax.swing.JTabbedPane();
        jTabbedPane57 = new javax.swing.JTabbedPane();
        jTabbedPane58 = new javax.swing.JTabbedPane();
        jTabbedPane14 = new javax.swing.JTabbedPane();
        jTabbedPane59 = new javax.swing.JTabbedPane();
        jTabbedPane60 = new javax.swing.JTabbedPane();
        jTabbedPane61 = new javax.swing.JTabbedPane();
        jTabbedPane62 = new javax.swing.JTabbedPane();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 30)); // NOI18N
        jLabel1.setText("FIRST NOEL CORPORATION");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(181, 181, 181)
                .add(jLabel1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        button1.setLabel("View Client Profile");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("Add Client");

        button3.setLabel("View Employee Profile");

        button4.setLabel("Add Employee");

        button5.setLabel("Generate Report");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(button3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(button1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(button2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(button4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(button5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(button2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(button3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(button4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(button5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("EMPLOYEE PROFILE");

        jLabel3.setText("Name of Employee:");

        jLabel4.setText("Juan V. Dela Cruz");

        jLabel5.setText("Age:");

        jLabel6.setText("21");

        jLabel7.setText("Sex:");

        jLabel8.setText("M");

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jTabbedPane3.addTab("Week 1", jTabbedPane15);
        jTabbedPane3.addTab("Week 2", jTabbedPane16);
        jTabbedPane3.addTab("Week 3", jTabbedPane17);
        jTabbedPane3.addTab("Week 4", jTabbedPane18);

        jTabbedPane2.addTab("January", jTabbedPane3);

        jTabbedPane4.addTab("Week 1", jTabbedPane19);
        jTabbedPane4.addTab("Week 2", jTabbedPane20);
        jTabbedPane4.addTab("Week 3", jTabbedPane21);
        jTabbedPane4.addTab("Week 4", jTabbedPane22);

        jTabbedPane2.addTab("February", jTabbedPane4);

        jTabbedPane5.addTab("Week 1", jTabbedPane23);
        jTabbedPane5.addTab("Week 2", jTabbedPane24);
        jTabbedPane5.addTab("Week 3", jTabbedPane25);
        jTabbedPane5.addTab("Week 4", jTabbedPane26);

        jTabbedPane2.addTab("March", jTabbedPane5);

        jTabbedPane6.addTab("Week 1", jTabbedPane27);
        jTabbedPane6.addTab("Week 2", jTabbedPane28);
        jTabbedPane6.addTab("Week 3", jTabbedPane29);
        jTabbedPane6.addTab("Week 4", jTabbedPane30);

        jTabbedPane2.addTab("April", jTabbedPane6);

        jTabbedPane7.addTab("Week 1", jTabbedPane31);
        jTabbedPane7.addTab("Week 2", jTabbedPane32);
        jTabbedPane7.addTab("Week 3", jTabbedPane33);
        jTabbedPane7.addTab("Week 4", jTabbedPane34);

        jTabbedPane2.addTab("May", jTabbedPane7);

        jTabbedPane8.addTab("Week 1", jTabbedPane35);
        jTabbedPane8.addTab("Week 2", jTabbedPane36);
        jTabbedPane8.addTab("Week 3", jTabbedPane37);
        jTabbedPane8.addTab("Week 4", jTabbedPane38);

        jTabbedPane2.addTab("June", jTabbedPane8);

        jTabbedPane9.addTab("Week 1", jTabbedPane39);
        jTabbedPane9.addTab("Week 2", jTabbedPane40);
        jTabbedPane9.addTab("Week 3", jTabbedPane41);
        jTabbedPane9.addTab("Week 4", jTabbedPane42);

        jTabbedPane2.addTab("July", jTabbedPane9);

        jTabbedPane10.addTab("Week 1", jTabbedPane43);
        jTabbedPane10.addTab("Week 2", jTabbedPane44);
        jTabbedPane10.addTab("Week 3", jTabbedPane45);
        jTabbedPane10.addTab("Week 4", jTabbedPane46);

        jTabbedPane2.addTab("August", jTabbedPane10);

        jTabbedPane11.addTab("Week 1", jTabbedPane47);
        jTabbedPane11.addTab("Week 2", jTabbedPane48);
        jTabbedPane11.addTab("Week 3", jTabbedPane49);
        jTabbedPane11.addTab("Week 4", jTabbedPane50);

        jTabbedPane2.addTab("September", jTabbedPane11);

        jTabbedPane12.addTab("Week 1", jTabbedPane51);
        jTabbedPane12.addTab("Week 2", jTabbedPane52);
        jTabbedPane12.addTab("Week 3", jTabbedPane53);
        jTabbedPane12.addTab("Week 4", jTabbedPane54);

        jTabbedPane2.addTab("October", jTabbedPane12);

        jTabbedPane13.addTab("Week 1", jTabbedPane55);
        jTabbedPane13.addTab("Week 2", jTabbedPane56);
        jTabbedPane13.addTab("Week 3", jTabbedPane57);
        jTabbedPane13.addTab("Week 4", jTabbedPane58);

        jTabbedPane2.addTab("November", jTabbedPane13);

        jTabbedPane14.addTab("Week 1", jTabbedPane59);
        jTabbedPane14.addTab("Week 2", jTabbedPane60);
        jTabbedPane14.addTab("Week 3", jTabbedPane61);
        jTabbedPane14.addTab("Week 4", jTabbedPane62);

        jTabbedPane2.addTab("December", jTabbedPane14);

        jLabel9.setText("Search Employee:");

        jTextField1.setText("Enter Name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(197, 197, 197)
                        .add(jLabel9))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel3)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel8)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(jLabel6))))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jButton1)))
                .add(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(3, 3, 3)
                        .add(jButton1))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(jLabel8)
                            .add(jLabel6)
                            .add(jLabel5))
                        .add(13, 13, 13)))
                .add(18, 18, 18)
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 461, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 715, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane13;
    private javax.swing.JTabbedPane jTabbedPane14;
    private javax.swing.JTabbedPane jTabbedPane15;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane19;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane20;
    private javax.swing.JTabbedPane jTabbedPane21;
    private javax.swing.JTabbedPane jTabbedPane22;
    private javax.swing.JTabbedPane jTabbedPane23;
    private javax.swing.JTabbedPane jTabbedPane24;
    private javax.swing.JTabbedPane jTabbedPane25;
    private javax.swing.JTabbedPane jTabbedPane26;
    private javax.swing.JTabbedPane jTabbedPane27;
    private javax.swing.JTabbedPane jTabbedPane28;
    private javax.swing.JTabbedPane jTabbedPane29;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane30;
    private javax.swing.JTabbedPane jTabbedPane31;
    private javax.swing.JTabbedPane jTabbedPane32;
    private javax.swing.JTabbedPane jTabbedPane33;
    private javax.swing.JTabbedPane jTabbedPane34;
    private javax.swing.JTabbedPane jTabbedPane35;
    private javax.swing.JTabbedPane jTabbedPane36;
    private javax.swing.JTabbedPane jTabbedPane37;
    private javax.swing.JTabbedPane jTabbedPane38;
    private javax.swing.JTabbedPane jTabbedPane39;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane40;
    private javax.swing.JTabbedPane jTabbedPane41;
    private javax.swing.JTabbedPane jTabbedPane42;
    private javax.swing.JTabbedPane jTabbedPane43;
    private javax.swing.JTabbedPane jTabbedPane44;
    private javax.swing.JTabbedPane jTabbedPane45;
    private javax.swing.JTabbedPane jTabbedPane46;
    private javax.swing.JTabbedPane jTabbedPane47;
    private javax.swing.JTabbedPane jTabbedPane48;
    private javax.swing.JTabbedPane jTabbedPane49;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane50;
    private javax.swing.JTabbedPane jTabbedPane51;
    private javax.swing.JTabbedPane jTabbedPane52;
    private javax.swing.JTabbedPane jTabbedPane53;
    private javax.swing.JTabbedPane jTabbedPane54;
    private javax.swing.JTabbedPane jTabbedPane55;
    private javax.swing.JTabbedPane jTabbedPane56;
    private javax.swing.JTabbedPane jTabbedPane57;
    private javax.swing.JTabbedPane jTabbedPane58;
    private javax.swing.JTabbedPane jTabbedPane59;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane60;
    private javax.swing.JTabbedPane jTabbedPane61;
    private javax.swing.JTabbedPane jTabbedPane62;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
